-- ### USER_GRP ### --

INSERT INTO ENT_AUDT(ENT_AUDT_ID,CRT_TS,CRT_USER_EMAIL,LAST_MODF_TS,LAST_MODF_USER_EMAIL) VALUES (5,now(),'sysadmin',null,null);
INSERT INTO USER_GRP (USER_GRP_ID,USER_GRP_NM,USER_GRP_DN,LCK_VERS_NR,ENT_AUDT_ID) VALUES (1,'GRP_01','Group 01',0,5);

INSERT INTO ENT_AUDT(ENT_AUDT_ID,CRT_TS,CRT_USER_EMAIL,LAST_MODF_TS,LAST_MODF_USER_EMAIL) VALUES (6,now(),'sysadmin',null,null);
INSERT INTO USER_GRP (USER_GRP_ID,USER_GRP_NM,USER_GRP_DN,LCK_VERS_NR,ENT_AUDT_ID) VALUES (2,'GRP_02','Group 02',0,6);

-- ### ACCT_USER_GRP ### --

INSERT INTO ACCT_USER_GRP (USER_GRP_ID,USER_ACCT_ID) VALUES
    ((SELECT USER_GRP_ID FROM USER_GRP WHERE USER_GRP_NM = 'GRP_01'), (SELECT USER_ACCT_ID FROM USER_ACCT WHERE EMAIL_ADDR = 'sysadmin')),
    ((SELECT USER_GRP_ID FROM USER_GRP WHERE USER_GRP_NM = 'GRP_02'), (SELECT USER_ACCT_ID FROM USER_ACCT WHERE EMAIL_ADDR = 'daniel@email.com')),
    ((SELECT USER_GRP_ID FROM USER_GRP WHERE USER_GRP_NM = 'GRP_01'), (SELECT USER_ACCT_ID FROM USER_ACCT WHERE EMAIL_ADDR = 'daniel@email.com'));
