-- ### USER_ACCT ### --

INSERT INTO ENT_AUDT(ENT_AUDT_ID,CRT_TS,CRT_USER_EMAIL,LAST_MODF_TS,LAST_MODF_USER_EMAIL) VALUES (1,now(),'none',null,null);
INSERT INTO USER_ACCT (USER_ACCT_ID,EMP_NR,EMAIL_ADDR,ACCT_ENBL,ACCT_EXP,ACCT_LCK,LCK_VERS_NR,ENT_AUDT_ID) VALUES 
    (1,0,'sysadmin',1,0,1,0,1);

INSERT INTO ENT_AUDT(ENT_AUDT_ID,CRT_TS,CRT_USER_EMAIL,LAST_MODF_TS,LAST_MODF_USER_EMAIL) VALUES (2,now(),'sysadmin',null,null);
INSERT INTO USER_ACCT (USER_ACCT_ID,EMP_NR,EMAIL_ADDR,ACCT_ENBL,ACCT_EXP,ACCT_LCK,LCK_VERS_NR,ENT_AUDT_ID) VALUES 
    (2,23069135,'daniel@email.com',1,0,0,0,2);
    
-- ### USER_ROLE ### --

INSERT INTO ENT_AUDT(ENT_AUDT_ID,CRT_TS,CRT_USER_EMAIL,LAST_MODF_TS,LAST_MODF_USER_EMAIL) VALUES (3,now(),'sysadmin',null,null);
INSERT INTO USER_ROLE (USER_ROLE_ID,USER_ROLE_NM,USER_ROLE_DN,LCK_VERS_NR,ENT_AUDT_ID) VALUES (1,'SYSADMIN','System Administrator',0,3);

INSERT INTO ENT_AUDT(ENT_AUDT_ID,CRT_TS,CRT_USER_EMAIL,LAST_MODF_TS,LAST_MODF_USER_EMAIL) VALUES (4,now(),'sysadmin',null,null);
INSERT INTO USER_ROLE (USER_ROLE_ID,USER_ROLE_NM,USER_ROLE_DN,LCK_VERS_NR,ENT_AUDT_ID) VALUES (2,'ADMIN','Administrator',0,4);

-- ### ACCT_USER_ROLE ### --

INSERT INTO ACCT_USER_ROLE (USER_ROLE_ID,USER_ACCT_ID) VALUES 
	((SELECT USER_ROLE_ID FROM USER_ROLE WHERE USER_ROLE_NM = 'SYSADMIN'),       (SELECT USER_ACCT_ID FROM USER_ACCT WHERE EMAIL_ADDR = 'sysadmin')),
    ((SELECT USER_ROLE_ID FROM USER_ROLE WHERE USER_ROLE_NM = 'ADMIN'),          (SELECT USER_ACCT_ID FROM USER_ACCT WHERE EMAIL_ADDR = 'daniel@email.com'));
